# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 1.py
# Created on: 2023-08-03 21:24:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 1 <底层元素> <顶层要素> <顶层要素__2_> <JX_规划范围线>
# Description:
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/beixiao/AppConfig/ArcGIS/Beixiao.tbx")

# Script arguments
# 底层元素 = "I:\\Beixiao\\Project\\J江东区临江控规\\临江控规_数据库.gdb\\YD_三调数据，规划范围内"
底层元素 = arcpy.GetParameterAsText(0)
if 底层元素 == "#" or not 底层元素:
    底层元素 = "YD_用地\\YD_三调"  # provide a default value if unspecified

# 顶层要素 = "I:\\Beixiao\\Project\\J江东区临江控规\\临江控规_数据库.gdb\\YD_三调细化和更正"
顶层要素 = arcpy.GetParameterAsText(1)
if 顶层要素 == "#" or not 顶层要素:
    顶层要素 = "YD_用地\\YD_三调细化和更正"  # provide a default value if unspecified

# 顶层要素__2_ = "I:\\Beixiao\\Project\\J江东区临江控规\\临江控规_数据库.gdb\\YD_用地审批信息，已实施"
顶层要素__2_ = arcpy.GetParameterAsText(2)
if 顶层要素__2_ == "#" or not 顶层要素__2_:
    顶层要素__2_ = "YD_用地\\YD_审批信息，已实施"  # provide a default value if unspecified


# JX_规划范围线 = "I:\\Beixiao\\Project\\J江东区临江控规\\临江控规_数据库.gdb\\JX_规划范围线"
JX_规划范围线 = arcpy.GetParameterAsText(3)
if JX_规划范围线 == "#" or not JX_规划范围线:
    JX_规划范围线 = "JX_规划范围线"  # provide a default value if unspecified

# Local variables:
合并1 = "C:\\Users\\beixiao\\Project\\J江东区临江控规\\临江控规_数据库.gdb\\AA_合并1"
合并2 = "C:\\Users\\beixiao\\Project\\J江东区临江控规\\临江控规_数据库.gdb\\AA_合并2"
DIST_用地现状图1 = "C:\\Users\\beixiao\\Project\\J江东区临江控规\\临江控规_数据库.gdb\\DIST_用地现状图1"

# Process: 合并用地图层
arcpy.gp.toolbox = "C:/Users/beixiao/AppConfig/ArcGIS/Beixiao.tbx"
# Warning: the toolbox C:/Users/beixiao/AppConfig/ArcGIS/Beixiao.tbx DOES NOT have an alias.
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.合并用地图层(...) with arcpy.合并用地图层_ALIAS(...)
arcpy.gp.合并用地图层(底层元素, 顶层要素, 合并1)

# Process: 合并用地图层 (2)
arcpy.gp.toolbox = "C:/Users/beixiao/AppConfig/ArcGIS/Beixiao.tbx"
# Warning: the toolbox C:/Users/beixiao/AppConfig/ArcGIS/Beixiao.tbx DOES NOT have an alias.
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.合并用地图层(...) with arcpy.合并用地图层_ALIAS(...)
arcpy.gp.合并用地图层(合并1, 顶层要素__2_, 合并2)

# Process: 常用_处理字段并裁剪
arcpy.gp.toolbox = "C:/Users/beixiao/AppConfig/ArcGIS/Beixiao.tbx"
# Warning: the toolbox C:/Users/beixiao/AppData/Roaming/ESRI/Desktop10.8/ArcToolbox/My Toolboxes/Beixiao.tbx DOES NOT have an alias.
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.输出到CAD前预处理2(...) with arcpy.输出到CAD前预处理2_ALIAS(...)
arcpy.gp.输出到CAD前预处理2(JX_规划范围线, DIST_用地现状图1, 合并2)
