# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-10-07 11:55:33
"""
# import arcpy
# from .ABCCADDEFG2 import ABCCADDEFG2
# from .ABCCADDEFG2 import ABCCADDEFG2
# from .ABCDEF1 import ABCDEF1
# from sys import argv
import bxarcpy


def main(
    工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb",
    输入要素名称="DIST_用地规划图",
    有种植属性的要素名称="CZ_三调筛选_种植属性名称",
):
    with bxarcpy.环境.环境管理器(临时工作空间=工作空间, 工作空间=工作空间):
        bxarcpy.配置.是否覆盖输出要素(True)

        用地要素 = bxarcpy.要素类.要素读取_通过名称(输入要素名称)
        用地要素.字段删除(["种植属性名称"])

        筛选后要素 = 用地要素.要素创建_通过筛选("地类编号 LIKE '02%' OR 地类编号 LIKE '03%' OR 地类编号 LIKE '04%'")
        筛选后要素.字段删除(保留字段名称列表=["地类编号"])

        有种植属性的要素 = bxarcpy.要素类.要素读取_通过名称(有种植属性的要素名称)
        有种植属性并且是两可用地的要素 = 有种植属性的要素.要素创建_通过相交([有种植属性的要素.名称])
        有种植属性并且是两可用地的要素.字段删除(保留字段名称列表=["种植属性名称"])

        更新两可后的用地要素 = 用地要素.要素创建_通过联合([有种植属性并且是两可用地的要素.名称])

        更新两可后的用地要素.字段删除(["Shape_Length_1", "Shape_Area_1"])

        更新两可后的用地要素.要素创建_通过复制并重命名重名要素(输入要素名称)


if __name__ == "__main__":
    main(
        工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb",
        输入要素名称="DIST_用地规划图",
        有种植属性的要素名称="CZ_三调筛选_种植属性名称",
    )
