[project]
name = "bxgis"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "vanadis91", email = "vanadis91@163.com"},
]
dependencies = []
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "GPLv3"}


[tool.pdm]
distribution = false
