# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-24 17:59:36
"""
import bxarcpy
from bxpy import 日志

# from sys import argv


def main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb", 输入要素名称列表=["YD_CAD色块1"], 输出CAD路径=r"C:\Users\beixiao\Desktop\001.dwg"):  # 拓扑_创建重叠检查拓扑
    with bxarcpy.类.环境.环境管理器(临时工作空间=工作空间, 工作空间=工作空间):
        # To allow overwriting outputs change overwriteOutput option to True.
        # arcpy.env.overwriteOutput = False
        bxarcpy.类.配置.是否覆盖输出要素 = True

        # Process: 创建要素数据集 (创建要素数据集) (management)
        数据库对象 = bxarcpy.类.数据库类.数据库读取_通过路径(工作空间)
        要素数据集名称列表 = 数据库对象.要素数据集名称列表获取()
        if "拓扑检查" in 要素数据集名称列表:
            bxarcpy.类.要素数据集类.要素数据集读取_通过名称("拓扑检查").要素数据集删除()
        要素数据集 = bxarcpy.类.要素数据集类.要素数据集创建("拓扑检查")
        # 新创建的要素集 = bxarcpy.数据管理.要素集创建(数据库=工作空间, 要素集名称="拓扑检查")
        拓扑对象 = bxarcpy.类.拓扑类.拓扑创建(要素数据集.名称, "拓扑")
        # Process: 创建拓扑 (创建拓扑) (management)
        # 拓扑 = bxarcpy.数据管理.拓扑创建(要素集=新创建的要素集, 拓扑名称="拓扑")

        # Process: 要素类至要素类 (要素类至要素类) (conversion)
        for x in 输入要素名称列表:
            输入要素 = bxarcpy.类.要素类.要素读取_通过名称(x)
            要素数据集中的要素 = 输入要素.导出到要素(要素数据集.名称 + "\\" + 输入要素.名称 + "_1")
            # 要素集中要素 = bxarcpy.转换.要素导出到要素(输入要素=输入要素, 输出路径=新创建的要素集, 输出文件名="AA_拓扑检查")

            # Process: 向拓扑中添加要素类 (向拓扑中添加要素类) (management)
            日志.输出调试(f"准备添加要素的名称是：{要素数据集中的要素.名称}")
            拓扑对象.拓扑中添加要素(要素数据集中的要素.名称)

            # Process: 添加拓扑规则 (添加拓扑规则) (management)
            if 要素数据集中的要素.几何类型 == "面":
                拓扑对象.拓扑中添加规则(要素数据集中的要素.名称, 规则="Must Not Overlap (Area)")
            elif 要素数据集中的要素.几何类型 == "线":
                拓扑对象.拓扑中添加规则(要素数据集中的要素.名称, 规则="Must Not Overlap (Line)")
                拓扑对象.拓扑中添加规则(要素数据集中的要素.名称, 规则="Must Not Self-Overlap (Line)")

            # Process: 拓扑验证 (拓扑验证) (management)
            拓扑对象.拓扑验证()

        拓扑导出后要素1, 拓扑导出后要素2, 拓扑导出后要素3 = 拓扑对象.导出到要素("AA_拓扑导出后要素")

        拓扑导出后要素3.导出到CAD(输出CAD路径)

        拓扑导出后要素1.要素删除()
        拓扑导出后要素2.要素删除()
        拓扑导出后要素3.要素删除()


if __name__ == "__main__":
    # Global Environment settings
    # main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb", 输入要素名称列表=["YD_审批信息已批未建", "YD_上位_粮食生产功能区", "YD_上位农用地落实_耕地质量提升", "YD_上位农用地落实_旱改水", "YD_上位农用地落实_垦造耕地", "YD_上位农用地落实_新增设施农用地", "YD_上位基本农田落实", "YD_GIS方案_农用地设计", "YD_CAD色块以外建设用地修改", "DIST_用地规划图"], 输出CAD路径=r"C:\Users\beixiao\Desktop\001.dwg")
    # main(工作空间=r"C:\Users\common\project\F富阳受降控规\受降北_数据库.gdb", 输入要素名称列表=["AA_CAD色块_拓扑检查"], 输出CAD路径=r"C:\Users\beixiao\Desktop\001.dwg")
    # main(工作空间=r"C:\\Users\\common\\project\\F富阳受降控规\\受降北_数据库.gdb", 输入要素="DIST_用地现状图", 输出CAD路径=r"C:\Users\beixiao\Desktop\001.dwg")
    main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb", 输入要素名称列表=["JX_工业片区范围线"], 输出CAD路径=r"C:\Users\beixiao\Desktop\001.dwg")
