# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-23 15:58:06
"""
import arcpy
import bxarcpy


def main(工作空间, 输入要素名称, 地类名称字段名称="地类名称"):
    with bxarcpy.类.环境.环境管理器(临时工作空间=工作空间, 工作空间=工作空间):
        # 用地_三调基数转换
        # To allow overwriting outputs change overwriteOutput option to True.
        # arcpy.env.overwriteOutput = False
        bxarcpy.类.配置.是否覆盖输出要素 = True

        # 地类转换表格 = "C:\\Users\\common\\AppConfig\\ArcGIS\\020.地类转换\\地类转换_三调与国空基数转换.xls\\Sheet1$"

        from bxpandas import 类 as pd

        a = pd.转换.excel转数据框架(r"C:\Users\beixiao\AppConfig\Bxcad\Config\设计配置\设计参数\地块_指标测算表.xlsx", 要读取的列=(1, 3, 4), 列数据类型={"性质名称": str, "地块性质": str, "地类标准": str})
        基数转换映射表 = pd.转换.数据框架转json(a)

        输入要素 = bxarcpy.要素类.要素读取_通过名称(输入要素名称)
        输入要素 = 输入要素.要素创建_通过复制()
        输入要素.字段添加("地类编号")
        with bxarcpy.类.游标类_用于更新(输入要素.名称, [地类名称字段名称, "地类编号"]) as cur:
            for cur1 in cur:
                对应的对象列表 = [基数转换映射表1 for 基数转换映射表1 in 基数转换映射表 if 基数转换映射表1["性质名称"] == cur1[0] and 基数转换映射表1["地类标准"] == "国空"]
                if 对应的对象列表:
                    cur.当前行更新([cur1[0], 对应的对象列表[0]["地块性质"]])
                else:
                    print(f"未找到该 地类名称 对应的 地类编号：{cur1[0]}")

        # try:
        #     输入要素.连接取消("Sheet1$")
        # except Exception as res:
        #     raise Exception(f"错误信息: {res}")
        # 输入要素.连接创建("地类编号", 地类转换表格, "三调编码")

        # 输入要素.字段计算(字段名称=输入要素名称 + ".地类编号_国空", 表达式="!Sheet1$.国空代码!")
        # 输入要素.字段计算(字段名称=输入要素名称 + ".基数转换关系", 表达式="!Sheet1$.转换类型!")

        输入要素.要素创建_通过复制并重命名重名要素(输入要素名称)

        # 输入要素.连接取消("Sheet1$")


if __name__ == "__main__":
    # Global Environment settings
    # main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb", 输入要素名称="YD_GIS方案")
    main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb", 输入要素名称="AA_test", 地类名称字段名称="JQXZYD")
