# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-18 22:36:50
"""
import bxarcpy
import time

# from sys import argv


def main(工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb", 调整前要素名称="YD_三调_初转换", 调整后要素名称="DIST_用地基期图"):
    # 用地_生成用地规划图
    with bxarcpy.类.环境.环境管理器(临时工作空间=工作空间, 工作空间=工作空间):
        bxarcpy.类.配置.是否覆盖输出要素 = True
        调整前要素 = bxarcpy.类.要素类.要素读取_通过名称(调整前要素名称)
        调整后要素 = bxarcpy.类.要素类.要素读取_通过名称(调整后要素名称)
        联合后要素 = 调整前要素.要素创建_通过联合([调整后要素.名称])
        联合后要素.字段添加("地类差异")
        with bxarcpy.类.游标类_用于更新(联合后要素.名称, ["地类编号", "地类编号_1", "地类差异"]) as cur:
            for cur1 in cur:
                if cur1[0] != cur1[1]:
                    cur1[2] = f"{cur1[0]} -> {cur1[1]}"
                cur.当前行更新([cur1[0], cur1[1], cur1[2]])
        联合后要素.要素创建_通过复制并重命名重名要素("AA_联合后要素", 数据库路径=工作空间)


if __name__ == "__main__":
    # Global Environment settings
    # AB1132(*argv[1:])
    main(
        工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb",
        调整前要素名称="YD_三调_初转换",
        调整后要素名称="DIST_用地基期图",
    )
