# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-18 22:36:50
"""
import bxarcpy
import time
from sys import argv


def main(工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb", 输出路径="\\DIST_用地现状图1", 规划范围="\\JX_规划范围线", 需要合并的要素列表=["\\YD_三调", "\\YD_三调细化和更正", "\\YD_审批信息，已实施"]):
    # 用地_生成用地规划图
    with bxarcpy.环境.环境管理器(临时工作空间=工作空间, 工作空间=工作空间):
        bxarcpy.配置.是否覆盖输出要素(False)

        底层要素 = 需要合并的要素列表[0]
        for x in 需要合并的要素列表[1:]:
            底层要素 = bxarcpy.分析.更新并合并字段(输入要素=底层要素, 更新要素=x)
            time.sleep(1.0)

        输出 = bxarcpy.分析.裁剪(输入要素=底层要素, 裁剪要素=规划范围, 输出要素=输出路径)


if __name__ == "__main__":
    # Global Environment settings
    # AB1132(*argv[1:])
    main(工作空间="C:\\Users\\common\\project\\F富阳受降控规\\受降北_数据库.gdb", 输出路径="\\DIST_用地现状图1", 规划范围="\\JX_规划范围线", 需要合并的要素列表=["\\YD_三调基数转换后_单元基期用地0925NEW", "\\YD_三调细化修改", "\\YD_不动产登记", "\\YD_审批信息"])
