# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-18 22:36:50
"""
import bxarcpy
import time
import bxpy

# from sys import argv


def main(工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb", 输出要素名称: str = "DIST_用地现状图", 规划范围="JX_规划范围线", 需要合并的要素名称列表: list = ["YD_三调", "YD_三调细化和更正", "YD_审批信息，已实施"], 是否拓扑检查=False):
    # 用地_生成用地规划图
    with bxarcpy.类.环境.环境管理器(临时工作空间=工作空间, 工作空间=工作空间):
        bxarcpy.类.配置.是否覆盖输出要素 = True

        底层要素 = bxarcpy.类.要素类.要素读取_通过名称(需要合并的要素名称列表[0])
        底层要素.字段删除(保留字段名称列表=["地类编号"])
        for x in 需要合并的要素名称列表[1:]:
            顶层要素 = bxarcpy.类.要素类.要素读取_通过名称(x)
            顶层要素.字段删除(保留字段名称列表=["地类编号"])
            底层要素 = 底层要素.要素创建_通过更新并合并字段(顶层要素.名称)
            time.sleep(1.0)
        裁剪后要素 = 底层要素.要素创建_通过裁剪(规划范围)
        裁剪后要素.要素创建_通过复制并重命名重名要素(输出要素名称)

        if 是否拓扑检查:
            import 拓扑_创建重叠检查拓扑

            需要拓扑的要素名称列表 = [x for x in 需要合并的要素名称列表]
            需要拓扑的要素名称列表.append(输出要素名称)
            拓扑_创建重叠检查拓扑.main(工作空间=工作空间, 输入要素名称列表=需要拓扑的要素名称列表, 输出CAD路径=r"C:\Users\beixiao\Desktop\拓扑检查.dwg")


if __name__ == "__main__":
    # Global Environment settings
    # AB1132(*argv[1:])
    # main(工作空间="C:\\Users\\common\\project\\F富阳受降控规\\受降北_数据库.gdb", 输出要素名称="DIST_用地现状图", 规划范围="JX_规划范围线", 需要合并的要素名称列表=["YD_基期", "YD_现状修改1", "YD_审批信息", "YD_审批信息_另一个", "YD_不动产登记", "YD_现状修改2"])
    # main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb", 输出要素名称="DIST_用地基期图", 规划范围="JX_规划范围线", 需要合并的要素名称列表=["YD_基期细化", "YD_农转用20年及以前"])
    bxpy.日志.开启()
    main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb", 输出要素名称="DIST_用地现状图", 规划范围="JX_规划范围线", 需要合并的要素名称列表=["YD_基期细化", "YD_农转用20年及以前", "YD_现状修改1", "YD_农转用21年及以后", "YD_审批信息已实施", "YD_地籍信息", "YD_现状修改2"], 是否拓扑检查=True)
