# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-18 22:36:50
"""
import bxarcpy
import time

# from sys import argv


def main(工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb", DIST_用地规划图="\\DIST_用地规划图1", AA_应在CAD中填色实际没填色="\\AA_应在CAD中填色实际没填色1", SQL_CAD地块中空隙的地类="'00'", SQL_以CAD为准的地类="地类编号 LIKE '060102%' OR 地类编号 LIKE '07%' OR 地类编号 LIKE '08%' OR 地类编号 LIKE '09%' OR 地类编号 LIKE '10%' OR 地类编号 LIKE '11%'  OR 地类编号 LIKE '12%'  OR 地类编号 LIKE '13%'  OR 地类编号 LIKE '14%'  OR 地类编号 LIKE '15%'  OR 地类编号 LIKE '16%'  OR ( 地类编号 LIKE '17%' AND 地类编号 NOT LIKE '1704%' AND 地类编号 NOT LIKE '1705%' )  OR 地类编号 LIKE '23%'"):
    # 用地_生成用地规划图
    with bxarcpy.环境.环境管理器(临时工作空间=工作空间, 工作空间=工作空间):
        bxarcpy.配置.是否覆盖输出要素(True)
        DIST_用地规划图 = 工作空间 + DIST_用地规划图
        AA_应在CAD中填色实际没填色 = 工作空间 + AA_应在CAD中填色实际没填色
        YD_CAD色块 = 工作空间 + "\\YD_CAD色块"
        JX_规划范围线 = 工作空间 + "\\JX_规划范围线"
        需合并的要素列表 = [f"{工作空间}\\YD_三调", f"{工作空间}\\YD_三调细化和更正", f"{工作空间}\\YD_审批信息，已实施", f"{工作空间}\\YD_审批信息，已批未建", f"{工作空间}\\YD_上位_粮食生产功能区", f"{工作空间}\\YD_上位农用地落实_耕地质量提升", f"{工作空间}\\YD_上位农用地落实_旱改水", f"{工作空间}\\YD_上位农用地落实_垦造耕地", f"{工作空间}\\YD_上位农用地落实_新增设施农用地", f"{工作空间}\\YD_上位基本农田落实", f"{工作空间}\\YD_GIS方案", f"{工作空间}\\YD_GIS方案_农用地设计", f"{工作空间}\\YD_CAD色块以外建设用地修改"]
        # 需合并的要素列表 = [f"{工作空间}\\YD_三调", f"{工作空间}\\YD_三调细化和更正", f"{工作空间}\\YD_审批信息，已实施", f"{工作空间}\\YD_审批信息，已批未建", f"{工作空间}\\YD_上位_粮食生产功能区", f"{工作空间}\\YD_上位农用地落实_耕地质量提升", f"{工作空间}\\YD_上位农用地落实_旱改水", f"{工作空间}\\YD_上位农用地落实_垦造耕地", f"{工作空间}\\YD_上位农用地落实_新增设施农用地", f"{工作空间}\\YD_上位基本农田落实", f"{工作空间}\\YD_GIS方案", f"{工作空间}\\YD_GIS方案_农用地设计", f"{工作空间}\\YD_CAD色块以外河道修改", f"{工作空间}\\YD_CAD色块以外建设用地修改"]

        填充空隙后 = bxarcpy.分析.填充空隙(输入要素=YD_CAD色块, 填充范围=JX_规划范围线, 填充地类编号表达式=SQL_CAD地块中空隙的地类)

        # Process: 筛选 (5) (选择) (analysis)
        YD_CAD色块_仅包含CAD中为准的色块 = bxarcpy.分析.筛选(输入要素=填充空隙后, SQL语句=SQL_以CAD为准的地类)

        # Process: 常用_合并用地图层 (常用_合并用地图层) ()
        底层要素 = 需合并的要素列表[0]
        for x in 需合并的要素列表[1:]:
            底层要素 = bxarcpy.分析.更新并合并字段(输入要素=底层要素, 更新要素=x)
            time.sleep(1.0)

        DIST_用地规划图1 = bxarcpy.分析.更新并合并字段(输入要素=底层要素, 更新要素=YD_CAD色块_仅包含CAD中为准的色块, 输出要素=DIST_用地规划图)

        删除字段 = ["dkbmgk", "地块性", "单元名", "TBYBH", "FID_DLTB", "GKXZ", "Layer", "CZCSXM", "三调地类名称", "三调地类编号", "ORIG_FID", "a", "镇街名称", "名称", "FID_4去除", "Shape_Leng", "三调稳", "二调永", "三调恢", "三调耕", "二调耕", "街道", "村名称", "组名", "序号", "FID_规划范围线_2303070850", "FWDGDHRLY", "SFWYYJJBNT", "WDGD", "BZ", "ZRSYX", "SJMC", "SJBH", "BHJSSJ", "BHKSSJ", "JZDZ", "LXDH", "ZRRMC", "ZRRZJHM", "ZZRR", "ZMC", "CFZR", "SJNF", "FRDBS", "ZLFLDM", "GDDJ", "GDDB", "ZZSXMC", "ZZSXDM", "TBXHMC", "TBXHDM", "GGBZL", "GDPDJB", "GDLX", "YJJBNTMJ", "KCMJ", "KCXS", "KCDLBM", "YJJBNTTBMJ", "ZLDWMC", "ZLDWDM", "QSDWMC", "QSDWDM", "QSXZ", "DLMC", "DLBM", "TBBH", "YJJBNTTBBH", "XZQMC", "XZQDM", "YSDM", "BSM", "FID_YJJBNTBHTB", "mj", "RefName", "LineWt", "Elevation", "Linetype", "Color", "Entity", "地块性质", "实体类型", "基数转换关系", "用途管制分区", "综合耕地N", "面积", "处理方向", "综合净面积"]
        DIST_用地规划图1 = bxarcpy.数据管理.字段删除(输入要素=DIST_用地规划图1, 删除字段列表=删除字段)

        # Process: 常用-擦除 (常用_擦除) ()
        非CAD中的色块 = bxarcpy.分析.擦除并几何修复(输入要素=DIST_用地规划图1, 擦除要素=YD_CAD色块_仅包含CAD中为准的色块)

        # Process: 筛选 (2) (选择) (analysis)
        AA_应在CAD中填色实际没填色 = bxarcpy.分析.筛选(输入要素=非CAD中的色块, SQL语句=SQL_以CAD为准的地类, 输出要素=AA_应在CAD中填色实际没填色)


if __name__ == "__main__":
    # Global Environment settings
    # AB1132(*argv[1:])
    main(
        工作空间="C:\\Users\\common\\project\\J江东区临江控规\\临江控规_数据库.gdb",
        DIST_用地规划图="\\DIST_用地规划图1",
        AA_应在CAD中填色实际没填色="\\AA_应在CAD中填色实际没填色1",
        SQL_CAD地块中空隙的地类="'00'",
        SQL_以CAD为准的地类="地类编号 LIKE '060102%' OR 地类编号 LIKE '07%' OR 地类编号 LIKE '08%' OR 地类编号 LIKE '09%' OR 地类编号 LIKE '10%' OR 地类编号 LIKE '11%'  OR 地类编号 LIKE '12%'  OR 地类编号 LIKE '13%'  OR 地类编号 LIKE '14%'  OR 地类编号 LIKE '15%'  OR 地类编号 LIKE '16%'  OR ( 地类编号 LIKE '17%' AND 地类编号 NOT LIKE '1704%' AND 地类编号 NOT LIKE '1705%' )  OR 地类编号 LIKE '23%'",
    )
