# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-19 00:16:10
"""
import arcpy
from sys import argv
import bxarcpy
from bxpy import 日志


def main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb"):  # 表达_设置符号系统
    with bxarcpy.环境.环境管理器(工作空间=工作空间, 临时工作空间=工作空间):
        # To allow overwriting outputs change overwriteOutput option to True.
        bxarcpy.配置.是否覆盖输出要素(True)
        # Process: 将图层符号系统与样式匹配 (将图层符号系统与样式匹配) (management)
        文档 = bxarcpy.类.文档类.文档读取_通过名称(文档路径=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.aprx")
        地图 = 文档.地图列表读取("ALL")[0]
        日志.输出调试(地图)
        图层 = 地图.图层列表读取("DIST_用地基期图")[0]
        日志.输出调试(图层)
        # 图层对象 = 图层.getDefinition("V3")
        # symLvl2 = 图层对象.renderer.symbol.symbol.symbolLayers[1]
        # symLvl2.color.values = [140, 70, 20, 20]
        # 图层.setDefinition(图层对象)

        # 样式1 = r"C:\Users\beixiao\AppConfig\ArcGIS\010.符号系统\符号系统_省国空地类_根据编号.lyrx"
        # 样式图层 = arcpy.mp.LayerFile(样式1).listLayers()[0]
        # 样式图层的符号 = 样式图层.listLayers()[0].symbology
        # 图层.symbology = 样式图层的符号

        样式2 = r"C:\Users\beixiao\AppConfig\ArcGIS\010.符号系统\符号系统_省国空地类_根据编号.lyr"
        图层.符号系统设置_通过lyr图层文件(图层文件路径=样式2, 映射关系=[["VALUE_FIELD", "", "JQYDDM"]])

        样式3 = r"C:\\Users\\beixiao\\AppConfig\\ArcGIS\\010.符号系统\\符号系统_省国空地类_根据编号.stylx"
        图层.符号系统设置_通过stylx样式文件(样式文件路径=样式3, 映射关系="$feature.JQYDDM")

        文档.文档另存为(r"C:\Users\beixiao\Desktop\003.aprx")
        # arcpy.RefreshTOC()
        # arcpy.RefreshActiveView()


if __name__ == "__main__":
    # Global Environment settings

    日志.开启()
    main(工作空间=r"C:\Users\common\project\J江东区临江控规\临江控规_数据库.gdb")
